version: "3.8"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ITPA
    restart: always
  web:
    build: .
    environment:
      MYSQL_DATABASE: ITPA
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      HTTPS: $DCT_HTTPS
      LP_URLS: $DTC_LP_URLS
    depends_on:
      - db
    restart: on-failure
    ports:
        - 5000:5000